#cloud-config
package_upgrade: true
runcmd:
 - [ 'sh', '-c', 'echo 1 > /proc/sys/net/ipv4/ip_forward']
 - [ 'iptables', '-t', 'nat', '-A', 'PREROUTING', '-p', 'tcp', '-i', 'eth0', '--dport', '10129', '-j', 'DNAT', '--to-destination', '185.46.212.88:10129' ]
 - [ 'iptables', '-t', 'nat', '-A', 'POSTROUTING', '-d', '185.46.212.88', '-j', 'MASQUERADE']