#cloud-config
package_upgrade: true
runcmd:
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
  - echo 'net.ipv6.conf.all.forwarding=1' >> /etc/sysctl.conf
  - echo 'net.ipv4.conf.all.accept_redirects = 0' >> /etc/sysctl.conf
  - echo 'net.ipv4.conf.all.send_redirects = 0' >> /etc/sysctl.conf
  - iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 10101 -j DNAT --to-destination 185.46.212.88:10101 -m comment --comment "forward port 10101 to zscaler"
  - iptables -t nat -A POSTROUTING -d 185.46.212.88 -j MASQUERADE -m comment --comment "snat traffic to zscaler"
  - echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections
  - echo iptables-persistent iptables-persistent/autosave_v6 boolean true | debconf-set-selections
  - apt install iptables-persistent -y