#cloud-config
package_upgrade: true
runcmd:
 - sysctl -w net.ipv4.ip_forward=1
 - iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 10101 -j DNAT --to-destination 185.46.212.88:10101 -m comment --comment "DNAT rule for port 10101"
 - iptables -t nat -A POSTROUTING -d 185.46.212.88 -j MASQUERADE -m comment --comment "SNAT rule for Zscaler traffic"